{
 "title": "CNV with ODF",
 "description": "some useful metrics for CNV and ODF",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Resource request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU request by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node) * on(node) group_left(role) kube_node_role{role=\"worker\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Request By node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}/1024/1024/1024) by (node) * on(node) group_left(role) kube_node_role{role=\"worker\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU request by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory request by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"f08-h12-000-1029u|f08-h13-000-1029u|f09-h02-000-1029u|f09-h03-000-1029u\"}/1024/1024/1024) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "ODF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "OSD Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_rss{pod=~\"rook-ceph-osd-(\\\\d+).*\", container!=\"\"}) by (pod), \"osd_label\", \"osd-$1\", \"pod\", \"rook-ceph-osd-(\\\\d+).*\") / 1024 / 1024 / 1024",
     "legendFormat": "{{osd_label}}"
    }
   ]
  },
  {
   "title": "OSD CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{pod=~\"rook-ceph-osd-(\\\\d+).*\", container!=\"\"}[1m])) by (pod), \"osd_label\", \"osd-$1\", \"pod\", \"rook-ceph-osd-(\\\\d+).*\")",
     "legendFormat": "{{osd_label}}"
    }
   ]
  },
  {
   "title": "Total Bandwidth by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{}[1m]) / 1024/1024/1024 * 8  + irate(node_network_transmit_bytes_total{}[1m])/1024/1024/1024 * 8) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CEPH Cluster IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r{}[1m])) ",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Physical Disk Latency (NVMe only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_time_seconds_total{device=~\"nvme.*\"}[1m]) / irate(node_disk_reads_completed_total{device=~\"nvme.*\"}[1m])) by (instance, device) * 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Physical Disk Read IOPS (NVMe only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{device=~\"nvme.*\"}[1m])) by (device, instance)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Physical disk write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_writes_completed_total{device=~\"nvme.*\"}[1m])) by (device, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CNV ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "label_replace(sum(container_memory_rss{pod=~\"virt-launcher.*\", container!=\"\"}) by (pod), \"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\") / 1024 / 1024 / 1024 ",
       "legendFormat": "{{vmi}}"
      }
     ]
    },
    {
     "title": "VM CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{pod=~\"virt-launcher.*\", container!=\"\"}[1m])) by (pod),\"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\")",
       "legendFormat": "{{vmi}}"
      }
     ]
    }
   ]
  }
 ]
}