{
 "title": "Descheduler with CNV",
 "description": "some useful metrics for Descheduler with CNV",
 "time": { "from": "2025-05-07T02:53:11.618Z", "to": "2025-05-07T03:45:46.829Z" },
 "panels": [
  { "title": "LoadAware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg CPU ultilization Across Workers & STDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (\n  1 - rate(node_cpu_seconds_total{mode='idle'}[1m]) * on(instance) \n  group_left() \n  (\n    label_replace(\n      kube_node_role{role=\"worker\"}, \n      'instance', '$1', \n      'node', '(.+)'\n    )\n  )\n)",
     "legendFormat": "Average "
    },
    {
     "expr": "stddev(\n  avg by (instance) (1 - rate(node_cpu_seconds_total{mode='idle'}[1m]) * on(instance) \n  group_left() \n  (\n    label_replace(\n      kube_node_role{role=\"worker\"}, \n      'instance', '$1', \n      'node', '(.+)'\n    )\n  )\n)\n)",
     "legendFormat": "STDEV"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg CPU ultilization By workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  1 - rate(node_cpu_seconds_total{mode='idle'}[1m]) * on(instance) \n  group_left() \n  label_replace(\n    kube_node_role{role=\"worker\"}, \n    'instance', '$1', \n    'node', '(.+)'\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Number of VMs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cnv:vmi_status_running:count)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Number of VM evicted ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_migration_succeeded)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Pressure Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg CPU pressure and STDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (rate(node_pressure_cpu_waiting_seconds_total[1m]) * on(instance) \n  group_left() \n  label_replace(\n    kube_node_role{role=\"worker\"}, \n    'instance', '$1', \n    'node', '(.+)'\n  ))",
     "legendFormat": "Avg"
    },
    {
     "expr": "stddev(\n  rate(node_pressure_cpu_waiting_seconds_total[1m])\n  * on(instance) group_left()\n  label_replace(\n    kube_node_role{role=\"worker\"},\n    \"instance\", \"$1\",\n    \"node\", \"(.+)\"\n  )\n)",
     "legendFormat": "STDEV"
    }
   ]
  },
  {
   "title": "CPU pressure by Worker Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total[1m]) * on(instance) \n  group_left() \n  label_replace(\n    kube_node_role{role=\"worker\"}, \n    'instance', '$1', \n    'node', '(.+)'\n  )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pod CPU Throttling Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory pressure by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_memory_waiting_seconds_total[15m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO pressure by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_io_waiting_seconds_total[1m])) by (instance) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU request by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU request by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node) * on(node) group_left(role) kube_node_role{role=\"worker\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory request by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"f08-h12-000-1029u|f08-h13-000-1029u|f09-h02-000-1029u|f09-h03-000-1029u\"}/1024/1024/1024) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Request By node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}/1024/1024/1024) by (node) * on(node) group_left(role) kube_node_role{role=\"worker\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "CNV ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_rss{pod=~\"virt-launcher.*\", container!=\"\"}) by (pod), \"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\") / 1024 / 1024 / 1024 ",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{pod=~\"virt-launcher.*\", container!=\"\"}[1m])) by (pod),\"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\")",
     "legendFormat": "{{vmi}}"
    }
   ]
  }
 ]
}