{
 "title": "descheduler with Virtualization",
 "description": "descheduler dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Network Ultilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TX bandwith ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{device!~\"eno12409np1\"}[1m])) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RX bandwith ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{device!~\"eno12409np1\"}[1m])) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "eucledian distance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "ideal_point_positive_distance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "descheduler:node:ideal_point_positive_distance:avg1m",
       "legendFormat": "{{instance}}"
      },
      { "legendFormat": "stdev" }
     ]
    },
    {
     "title": "linear_amplified_ideal_point_positive_distance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "descheduler:node:linear_amplified_ideal_point_positive_distance:k3:avg1m",
       "legendFormat": "{{instance}}"
      },
      { "legendFormat": "stdev" }
     ]
    }
   ]
  },
  {
   "title": "worker node memory ultlization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "average worker node memory utilization %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n  (\n    1 - avg_over_time(node_memory_MemAvailable_bytes[1m])\n    / on(instance) label_replace(kube_node_status_allocatable{resource=\"memory\"}, \"instance\", \"$1\", \"node\", \"(.+)\")\n  )\n  and on(instance)\n  label_replace(kube_node_status_allocatable{resource=\"memory\"}, \"instance\", \"$1\", \"node\", \"(.+)\") > 0\n  and on(instance)\n  label_replace(kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\")\n)",
       "legendFormat": "avg memory ultization"
      },
      {
       "expr": "stddev(\n  (\n    1 - avg_over_time(node_memory_MemAvailable_bytes[1m])\n    / on(instance) label_replace(kube_node_status_allocatable{resource=\"memory\"}, \"instance\", \"$1\", \"node\", \"(.+)\")\n  )\n  and on(instance)\n  label_replace(kube_node_status_allocatable{resource=\"memory\"}, \"instance\", \"$1\", \"node\", \"(.+)\") > 0\n  and on(instance)\n  label_replace(kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\")\n)",
       "legendFormat": "stdev"
      }
     ]
    },
    {
     "title": "worker memory utilization ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\n  node_memory_MemTotal_bytes\n  - node_memory_MemAvailable_bytes\n)\n* on(instance) group_left()\nlabel_replace(kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\")",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "worker node memory utilization percentage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  1 - avg_over_time(node_memory_MemAvailable_bytes[1m])\n      / on(instance) label_replace(kube_node_status_allocatable{resource=\"memory\"}, \"instance\", \"$1\", \"node\", \"(.+)\")\n)\nand on(instance)\n  label_replace(kube_node_status_allocatable{resource=\"memory\"}, \"instance\", \"$1\", \"node\", \"(.+)\") > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "worker node cpu ultlization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "avg worker cpu ultilization & stdev",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "    avg(\n      1 - rate(node_cpu_seconds_total{mode='idle'}[1m])\n      * on(instance) group_left()\n      (\n        label_replace(\n          kube_node_role{role=\"worker\"},\n          'instance', '$1',\n          'node', '(.+)'\n        )\n      )\n    )",
       "legendFormat": "Average "
      },
      {
       "expr": "stddev(\n  avg by (instance) (1 - rate(node_cpu_seconds_total{mode='idle'}[1m]) * on(instance) \n  group_left() \n  (\n    label_replace(\n      kube_node_role{role=\"worker\"}, \n      'instance', '$1', \n      'node', '(.+)'\n    )\n  )\n)\n)",
       "legendFormat": "STDEV"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "cpu ultilization per worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "   avg by (instance) (\n      1 - rate(node_cpu_seconds_total{mode='idle'}[1m])\n      * on(instance) group_left()\n      label_replace(kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\")\n    )",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "pressure metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu pressure avg workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n  avg by (instance) (rate(node_pressure_cpu_waiting_seconds_total[1m]))\n  and on(instance) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)')\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "cpu pressure per worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (instance) (rate(node_pressure_cpu_waiting_seconds_total[1m]))\nand on(instance) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)')",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memory pressure avg workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(descheduler:nodepressure:memory:avg1m * on(instance) group_left(node)\n        label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)'))\n",
       "legendFormat": "avg worker mem pressure"
      }
     ]
    },
    {
     "title": "memory pressure per worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "descheduler:nodepressure:memory:avg1m\nand on(instance) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)')",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "pod cpu throttling index",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "io pressure by node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(node_pressure_io_waiting_seconds_total[1m])) by (instance) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "resource usage overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "vm memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "label_replace(sum(container_memory_rss{pod=~\"virt-launcher.*\", container!=\"\"}) by (pod), \"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\") / 1024 / 1024 / 1024 ",
       "legendFormat": "{{vmi}}"
      }
     ]
    },
    {
     "title": "vm cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{pod=~\"virt-launcher.*\", container!=\"\"}[1m])) by (pod),\"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\")",
       "legendFormat": "{{vmi}}"
      }
     ]
    },
    {
     "title": "cpu request by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cpu request by node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node) * on(node) group_left(role) kube_node_role{role=\"worker\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "memory request by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"f08-h12-000-1029u|f08-h13-000-1029u|f09-h02-000-1029u|f09-h03-000-1029u\"}/1024/1024/1024) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "memory request by node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}/1024/1024/1024) by (node) * on(node) group_left(role) kube_node_role{role=\"worker\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "vm stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "total number of vms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(cnv:vmi_status_running:count)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "number of vms evicted ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kubevirt_vmi_migration_succeeded)",
       "legendFormat": "total_mirgrations"
      },
      {
       "expr": "sum(kubevirt_vmi_migration_succeeded{vmim=~\"workload.*\"})",
       "legendFormat": "workload-update"
      }
     ]
    }
   ]
  }
 ]
}