{
 "title": "hypershift-api-etcd",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Request Rate (SUM)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{namespace=~\"clusters-kv.*\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "wal fsync p99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket{namespace=~\"clusters-kv.*\"}[2m])) by (namespace, pod, le)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API request Read vs Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{namespace=~\"clusters-kv.*\", verb=~\"LIST|GET|WATCH\"}[2m])) by (namespace)",
     "legendFormat": "read - {{namespace}}"
    },
    {
     "expr": "sum(rate(apiserver_request_total{namespace=~\"clusters-kv.*\", verb=~\"POST|PUT|PATCH|UPDATE|DELETE|APPLY\"}[2m])) by (namespace)",
     "legendFormat": "write - {{namespace}}"
    }
   ]
  },
  {
   "title": "disk backend commit p99 ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_backend_commit_duration_seconds_bucket{namespace=~\"clusters-kv.*\"}[2m])) by (namespace, pod, le)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control Plane Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"clusters-kv.*\", container!=\"POD\",container!=\"\", pod!=\"\", pod!~\"virt-launcher.*|importer-kv.*\"}/1024/1024/1024) by (namespace)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD DISK IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{device=\"nvme0n1\", instance=~\"worker002-1029p|worker003-1029p|worker001-1029p\"} [2m]) ) by (instance)",
     "legendFormat": "Read - {{instance}}"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{device=\"nvme0n1\",instance=~\"worker002-1029p|worker003-1029p|worker001-1029p\"}[2m])) by (instance)",
     "legendFormat": "Write - {{instance}}"
    }
   ]
  },
  {
   "title": "Control Plane CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"clusters-kv.*\",container!=\"POD\",name!=\"\", container!=\"\", pod!=\"\", pod!~\"virt-launcher-kv-.*|importer-kv.*\"}[2m])*100) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Disk Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=\"nvme0n1\", instance=~\"worker002-1029p|worker003-1029p|worker001-1029p\"}[2m]) / 1024 / 1024) by (instance)",
     "legendFormat": "Read - {{instance}} "
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=\"nvme0n1\", instance=~\"worker002-1029p|worker003-1029p|worker001-1029p\"}[2m]) / 1024 / 1024) by (instance)",
     "legendFormat": "Write - {{instance}}"
    }
   ]
  },
  {
   "title": "vm worker mem usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"clusters-kv.*\", container!=\"POD\", container!=\"\", pod!=\"\", pod=~\"virt-launcher.*|importer-kv.*\"}/1024/1024/1024) by (namespace)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "virt components & system reserve mem usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"openshift-cnv\", container!=\"POD\", container!=\"\", pod!=\"\", pod=~\"virt-api.*|virt-control.*\"}/1024/1024) by (pod)  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (container_memory_rss{id=\"/system.slice\"}/1024/1024) > ((sum by (node) (kube_node_status_capacity{resource=\"memory\"} - kube_node_status_allocatable{resource=\"memory\"})/1024/1024) * 0.95)",
     "legendFormat": "system - {{node}}"
    }
   ]
  },
  {
   "title": "Core DNS error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "(sum by (namespace) (rate(coredns_dns_responses_total{rcode=\"SERVFAIL\"}[5m])) / sum by (namespace) (rate(coredns_dns_responses_total[5m]))) > 0.01",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd slow operations & leader change",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_slow_apply_total{namespace=~\"clusters-kv.*\"}[2m]))",
     "legendFormat": "slow apply "
    },
    {
     "expr": "sum(rate(etcd_server_slow_read_indexes_total{namespace=~\"clusters-kv.*\"}[2m]))",
     "legendFormat": "slow read index"
    },
    {
     "expr": "sum(rate(etcd_server_leader_changes_seen_total{namespace=~\"clusters-kv.*\"}[2m]))",
     "legendFormat": "leader change "
    }
   ]
  },
  {
   "title": "etcd fragmentation ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(last_over_time(etcd_mvcc_db_total_size_in_use_in_bytes[5m]) / last_over_time(etcd_mvcc_db_total_size_in_bytes[5m])) < 0.5",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Kube Client Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "(sum by (cluster, instance, job, namespace) (rate(rest_client_requests_total{code=~\"5..\"}[5m])) / sum by (cluster, instance, job, namespace) (rate(rest_client_requests_total[5m]))) > 0.01",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}